services:
  db:
    image: postgres:16.3
    container_name: db
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydiplom
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  app1:
    image: 'myapp:5.7'
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  postgres_data: