server:
  port: 8080
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydiplom
    username: root
    password: root
    initialization-mode: always
